spring: #띄어쓰기 없음
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/test;NON_KEYWORDS=USER #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: 127.0.0.1
    port: 6379

  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
#        show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
  mail:
#   host, port는 naver에서 정해준 값
    host: smtp.naver.com
    port: 465
#   본인 naver 계정정보 삽입
    username: leojung1505@naver.com
    password: v79jpx0909
#   전송하기 위한 prop으로 ssl의 신뢰, 권한 등 사용허가
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com

logging.level: #띄어쓰기 없음
  org.hibernate.SQL: debug #띄어쓰기 2칸
  org.hibernate.type: trace #띄어쓰기 2칸

